# Generated by Django 6.0.2 on 2026-02-20 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('deposit_required', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membership Plan',
                'verbose_name_plural': 'Membership Plans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('space_type', models.CharField(choices=[('studio', 'Studio'), ('storage', 'Storage'), ('parking', 'Parking'), ('desk', 'Desk'), ('other', 'Other')], max_length=20)),
                ('size_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('manual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='spaces/')),
                ('floorplan_ref', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Space',
                'verbose_name_plural': 'Spaces',
                'ordering': ['space_id'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_legal_name', models.CharField(max_length=255)),
                ('preferred_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('former', 'Former'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('role', models.CharField(choices=[('standard', 'Standard'), ('guild_lead', 'Guild Lead'), ('work_trade', 'Work-Trade'), ('employee', 'Employee'), ('contractor', 'Contractor'), ('volunteer', 'Volunteer')], default='standard', max_length=20)),
                ('join_date', models.DateField()),
                ('cancellation_date', models.DateField(blank=True, null=True)),
                ('committed_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('membership_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='membership.membershipplan')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['full_legal_name'],
            },
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_type', models.CharField(choices=[('month_to_month', 'Month-to-Month'), ('annual', 'Annual')], max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('committed_until', models.DateField(blank=True, null=True)),
                ('deposit_required', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('deposit_paid_date', models.DateField(blank=True, null=True)),
                ('deposit_paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='membership.member')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='membership.space')),
            ],
            options={
                'verbose_name': 'Lease',
                'verbose_name_plural': 'Leases',
                'ordering': ['-start_date'],
            },
        ),
    ]
